# Generated by Django 5.0.6 on 2024-07-03 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.buyer'),
        ),
    ]
