# Generated by Django 4.2.14 on 2024-08-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='coverLetter',
            field=models.TextField(default='hehe', max_length=500),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='priceRange',
            field=models.PositiveIntegerField(default='1000', max_length=5),
        ),
    ]
