# Generated by Django 5.0.6 on 2024-07-08 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.buyer'),
        ),
    ]
