# Generated by Django 4.2.14 on 2024-08-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_applyjob_coverletter_applyjob_pricerange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='coverLetter',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='priceRange',
            field=models.PositiveIntegerField(max_length=5),
        ),
    ]
