# Generated by Django 5.0.6 on 2024-07-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPECIALITY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
