# Generated by Django 4.2.14 on 2024-09-11 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_applyjob_coverletter_alter_applyjob_pricerange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='user',
        ),
        migrations.AddField(
            model_name='applyjob',
            name='seller',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jobs.seller'),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='priceRange',
            field=models.PositiveIntegerField(),
        ),
    ]
