# Generated by Django 4.2.14 on 2024-07-25 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_budget_alter_job_expertise_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirement',
            field=models.TextField(),
        ),
    ]
