# Generated by Django 4.2.14 on 2024-09-11 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_applyjob_user_applyjob_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.seller'),
        ),
    ]
