# Generated by Django 4.2.14 on 2024-07-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_budget_alter_job_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='profile_pic',
            field=models.ImageField(upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='profile_pic',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
