# Generated by Django 4.2.14 on 2024-09-11 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0005_alter_applyjob_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='seller',
        ),
        migrations.AddField(
            model_name='applyjob',
            name='User',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
