# Generated by Django 4.2.14 on 2024-09-13 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_applyjob_user_notification_applyjob_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-timestamp']},
        ),
    ]
